// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nso_service.proto

package nso_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Response struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe9e6289be376b44, []int{0}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type Request struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe9e6289be376b44, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// Get devices messages
type Device struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              string      `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Type                 *DeviceType `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Authgroup            string      `protobuf:"bytes,4,opt,name=authgroup,proto3" json:"authgroup,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe9e6289be376b44, []int{2}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Device) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Device) GetType() *DeviceType {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Device) GetAuthgroup() string {
	if m != nil {
		return m.Authgroup
	}
	return ""
}

type DeviceType struct {
	NedId                string   `protobuf:"bytes,1,opt,name=ned_id,json=nedId,proto3" json:"ned_id,omitempty"`
	NedType              string   `protobuf:"bytes,2,opt,name=ned_type,json=nedType,proto3" json:"ned_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceType) Reset()         { *m = DeviceType{} }
func (m *DeviceType) String() string { return proto.CompactTextString(m) }
func (*DeviceType) ProtoMessage()    {}
func (*DeviceType) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe9e6289be376b44, []int{3}
}

func (m *DeviceType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceType.Unmarshal(m, b)
}
func (m *DeviceType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceType.Marshal(b, m, deterministic)
}
func (m *DeviceType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceType.Merge(m, src)
}
func (m *DeviceType) XXX_Size() int {
	return xxx_messageInfo_DeviceType.Size(m)
}
func (m *DeviceType) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceType.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceType proto.InternalMessageInfo

func (m *DeviceType) GetNedId() string {
	if m != nil {
		return m.NedId
	}
	return ""
}

func (m *DeviceType) GetNedType() string {
	if m != nil {
		return m.NedType
	}
	return ""
}

type GetDevicesRequest struct {
	Request              *Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDevicesRequest) Reset()         { *m = GetDevicesRequest{} }
func (m *GetDevicesRequest) String() string { return proto.CompactTextString(m) }
func (*GetDevicesRequest) ProtoMessage()    {}
func (*GetDevicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe9e6289be376b44, []int{4}
}

func (m *GetDevicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDevicesRequest.Unmarshal(m, b)
}
func (m *GetDevicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDevicesRequest.Marshal(b, m, deterministic)
}
func (m *GetDevicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDevicesRequest.Merge(m, src)
}
func (m *GetDevicesRequest) XXX_Size() int {
	return xxx_messageInfo_GetDevicesRequest.Size(m)
}
func (m *GetDevicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDevicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDevicesRequest proto.InternalMessageInfo

func (m *GetDevicesRequest) GetRequest() *Request {
	if m != nil {
		return m.Request
	}
	return nil
}

type GetDevicesResponse struct {
	Response             *Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Devices              []*Device `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetDevicesResponse) Reset()         { *m = GetDevicesResponse{} }
func (m *GetDevicesResponse) String() string { return proto.CompactTextString(m) }
func (*GetDevicesResponse) ProtoMessage()    {}
func (*GetDevicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe9e6289be376b44, []int{5}
}

func (m *GetDevicesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDevicesResponse.Unmarshal(m, b)
}
func (m *GetDevicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDevicesResponse.Marshal(b, m, deterministic)
}
func (m *GetDevicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDevicesResponse.Merge(m, src)
}
func (m *GetDevicesResponse) XXX_Size() int {
	return xxx_messageInfo_GetDevicesResponse.Size(m)
}
func (m *GetDevicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDevicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDevicesResponse proto.InternalMessageInfo

func (m *GetDevicesResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GetDevicesResponse) GetDevices() []*Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

// Exec operation messages
type ExecOperationRequest struct {
	Request              *Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Options              string   `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	JsonData             string   `protobuf:"bytes,4,opt,name=json_data,json=jsonData,proto3" json:"json_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecOperationRequest) Reset()         { *m = ExecOperationRequest{} }
func (m *ExecOperationRequest) String() string { return proto.CompactTextString(m) }
func (*ExecOperationRequest) ProtoMessage()    {}
func (*ExecOperationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe9e6289be376b44, []int{6}
}

func (m *ExecOperationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecOperationRequest.Unmarshal(m, b)
}
func (m *ExecOperationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecOperationRequest.Marshal(b, m, deterministic)
}
func (m *ExecOperationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecOperationRequest.Merge(m, src)
}
func (m *ExecOperationRequest) XXX_Size() int {
	return xxx_messageInfo_ExecOperationRequest.Size(m)
}
func (m *ExecOperationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecOperationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecOperationRequest proto.InternalMessageInfo

func (m *ExecOperationRequest) GetRequest() *Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *ExecOperationRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ExecOperationRequest) GetOptions() string {
	if m != nil {
		return m.Options
	}
	return ""
}

func (m *ExecOperationRequest) GetJsonData() string {
	if m != nil {
		return m.JsonData
	}
	return ""
}

type ExecOperationResponse struct {
	Response             *Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ExecOperationResponse) Reset()         { *m = ExecOperationResponse{} }
func (m *ExecOperationResponse) String() string { return proto.CompactTextString(m) }
func (*ExecOperationResponse) ProtoMessage()    {}
func (*ExecOperationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe9e6289be376b44, []int{7}
}

func (m *ExecOperationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecOperationResponse.Unmarshal(m, b)
}
func (m *ExecOperationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecOperationResponse.Marshal(b, m, deterministic)
}
func (m *ExecOperationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecOperationResponse.Merge(m, src)
}
func (m *ExecOperationResponse) XXX_Size() int {
	return xxx_messageInfo_ExecOperationResponse.Size(m)
}
func (m *ExecOperationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecOperationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecOperationResponse proto.InternalMessageInfo

func (m *ExecOperationResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

// Get config messages
type GetConfigRequest struct {
	Request              *Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Options              string   `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigRequest) Reset()         { *m = GetConfigRequest{} }
func (m *GetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GetConfigRequest) ProtoMessage()    {}
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe9e6289be376b44, []int{8}
}

func (m *GetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigRequest.Unmarshal(m, b)
}
func (m *GetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigRequest.Marshal(b, m, deterministic)
}
func (m *GetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigRequest.Merge(m, src)
}
func (m *GetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GetConfigRequest.Size(m)
}
func (m *GetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigRequest proto.InternalMessageInfo

func (m *GetConfigRequest) GetRequest() *Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *GetConfigRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *GetConfigRequest) GetOptions() string {
	if m != nil {
		return m.Options
	}
	return ""
}

type GetConfigResponse struct {
	Response             *Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetConfigResponse) Reset()         { *m = GetConfigResponse{} }
func (m *GetConfigResponse) String() string { return proto.CompactTextString(m) }
func (*GetConfigResponse) ProtoMessage()    {}
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe9e6289be376b44, []int{9}
}

func (m *GetConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigResponse.Unmarshal(m, b)
}
func (m *GetConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigResponse.Marshal(b, m, deterministic)
}
func (m *GetConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigResponse.Merge(m, src)
}
func (m *GetConfigResponse) XXX_Size() int {
	return xxx_messageInfo_GetConfigResponse.Size(m)
}
func (m *GetConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigResponse proto.InternalMessageInfo

func (m *GetConfigResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

// Edit config messages
type EditConfigRequest struct {
	Request              *Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	OperationType        string   `protobuf:"bytes,3,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	Options              string   `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	JsonData             string   `protobuf:"bytes,5,opt,name=json_data,json=jsonData,proto3" json:"json_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditConfigRequest) Reset()         { *m = EditConfigRequest{} }
func (m *EditConfigRequest) String() string { return proto.CompactTextString(m) }
func (*EditConfigRequest) ProtoMessage()    {}
func (*EditConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe9e6289be376b44, []int{10}
}

func (m *EditConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditConfigRequest.Unmarshal(m, b)
}
func (m *EditConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditConfigRequest.Marshal(b, m, deterministic)
}
func (m *EditConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditConfigRequest.Merge(m, src)
}
func (m *EditConfigRequest) XXX_Size() int {
	return xxx_messageInfo_EditConfigRequest.Size(m)
}
func (m *EditConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditConfigRequest proto.InternalMessageInfo

func (m *EditConfigRequest) GetRequest() *Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *EditConfigRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *EditConfigRequest) GetOperationType() string {
	if m != nil {
		return m.OperationType
	}
	return ""
}

func (m *EditConfigRequest) GetOptions() string {
	if m != nil {
		return m.Options
	}
	return ""
}

func (m *EditConfigRequest) GetJsonData() string {
	if m != nil {
		return m.JsonData
	}
	return ""
}

type EditConfigResponse struct {
	Response             *Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EditConfigResponse) Reset()         { *m = EditConfigResponse{} }
func (m *EditConfigResponse) String() string { return proto.CompactTextString(m) }
func (*EditConfigResponse) ProtoMessage()    {}
func (*EditConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe9e6289be376b44, []int{11}
}

func (m *EditConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditConfigResponse.Unmarshal(m, b)
}
func (m *EditConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditConfigResponse.Marshal(b, m, deterministic)
}
func (m *EditConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditConfigResponse.Merge(m, src)
}
func (m *EditConfigResponse) XXX_Size() int {
	return xxx_messageInfo_EditConfigResponse.Size(m)
}
func (m *EditConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditConfigResponse proto.InternalMessageInfo

func (m *EditConfigResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

// Query
type QueryRequest struct {
	Request              *Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	JsonQuery            string   `protobuf:"bytes,2,opt,name=json_query,json=jsonQuery,proto3" json:"json_query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe9e6289be376b44, []int{12}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetRequest() *Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *QueryRequest) GetJsonQuery() string {
	if m != nil {
		return m.JsonQuery
	}
	return ""
}

type QueryResponse struct {
	Response             *Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe9e6289be376b44, []int{13}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Device)(nil), "Device")
	proto.RegisterType((*DeviceType)(nil), "DeviceType")
	proto.RegisterType((*GetDevicesRequest)(nil), "GetDevicesRequest")
	proto.RegisterType((*GetDevicesResponse)(nil), "GetDevicesResponse")
	proto.RegisterType((*ExecOperationRequest)(nil), "ExecOperationRequest")
	proto.RegisterType((*ExecOperationResponse)(nil), "ExecOperationResponse")
	proto.RegisterType((*GetConfigRequest)(nil), "GetConfigRequest")
	proto.RegisterType((*GetConfigResponse)(nil), "GetConfigResponse")
	proto.RegisterType((*EditConfigRequest)(nil), "EditConfigRequest")
	proto.RegisterType((*EditConfigResponse)(nil), "EditConfigResponse")
	proto.RegisterType((*QueryRequest)(nil), "QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "QueryResponse")
}

func init() {
	proto.RegisterFile("nso_service.proto", fileDescriptor_fe9e6289be376b44)
}

var fileDescriptor_fe9e6289be376b44 = []byte{
	// 526 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x56, 0xd2, 0xfc, 0x79, 0x42, 0x2a, 0x32, 0x6d, 0x2a, 0x63, 0x40, 0x0d, 0x2b, 0x15, 0xe5,
	0xb4, 0x07, 0xa3, 0x82, 0x04, 0x52, 0x2e, 0xb4, 0xaa, 0xb8, 0x50, 0xd5, 0xe5, 0x4c, 0x64, 0xba,
	0x43, 0x6b, 0x7e, 0x76, 0x5d, 0xef, 0x1a, 0x91, 0x07, 0xe0, 0x15, 0x78, 0x07, 0xde, 0x12, 0x79,
	0xbd, 0x4e, 0xd2, 0x24, 0x42, 0xb2, 0x44, 0x6f, 0xbb, 0x33, 0x9e, 0xd9, 0xef, 0x9b, 0xef, 0x1b,
	0xc3, 0x50, 0x6a, 0x35, 0xd3, 0x94, 0xfd, 0x48, 0xae, 0x88, 0xa7, 0x99, 0x32, 0x8a, 0x31, 0xe8,
	0x45, 0xa4, 0x53, 0x25, 0x35, 0xe1, 0x01, 0x74, 0x32, 0xd2, 0xf9, 0x37, 0xe3, 0x37, 0xc6, 0x8d,
	0x89, 0x17, 0xb9, 0x1b, 0x3b, 0x84, 0x6e, 0x44, 0xb7, 0x39, 0x69, 0x83, 0xfb, 0xd0, 0x36, 0xea,
	0x2b, 0x49, 0xf7, 0x45, 0x79, 0x61, 0x39, 0x74, 0x4e, 0xa8, 0x68, 0x8a, 0x08, 0x2d, 0x19, 0x7f,
	0x27, 0x97, 0xb6, 0x67, 0xf4, 0xa1, 0x1b, 0x0b, 0x91, 0x91, 0xd6, 0x7e, 0xd3, 0x86, 0xab, 0x2b,
	0x1e, 0x42, 0xcb, 0xcc, 0x53, 0xf2, 0x77, 0xc6, 0x8d, 0x49, 0x3f, 0xec, 0xf3, 0xb2, 0xc9, 0x87,
	0x79, 0x4a, 0x91, 0x4d, 0xe0, 0x13, 0xf0, 0xe2, 0xdc, 0xdc, 0x5c, 0x67, 0x2a, 0x4f, 0xfd, 0x96,
	0x2d, 0x5e, 0x06, 0xd8, 0x14, 0x60, 0x59, 0x81, 0x23, 0xe8, 0x48, 0x12, 0xb3, 0x44, 0x54, 0xd8,
	0x24, 0x89, 0x77, 0x02, 0x1f, 0x41, 0xaf, 0x08, 0xdb, 0x77, 0xdc, 0xf3, 0x92, 0x44, 0x51, 0xc1,
	0x5e, 0xc1, 0xf0, 0x8c, 0x4c, 0xd9, 0x42, 0x57, 0x0c, 0x19, 0x74, 0xb3, 0xf2, 0x68, 0xfb, 0xf4,
	0xc3, 0x1e, 0x77, 0xa9, 0xa8, 0x4a, 0xb0, 0x8f, 0x80, 0xab, 0x85, 0x6e, 0x7c, 0x47, 0xd0, 0xcb,
	0xdc, 0xd9, 0x95, 0x7a, 0xbc, 0x4a, 0x46, 0x8b, 0x14, 0x3e, 0x83, 0xae, 0x28, 0x2b, 0xfd, 0xe6,
	0x78, 0x67, 0xd2, 0x0f, 0xbb, 0x8e, 0x77, 0x54, 0xc5, 0xd9, 0xaf, 0x06, 0xec, 0x9f, 0xfe, 0xa4,
	0xab, 0xf3, 0x94, 0xb2, 0xd8, 0x24, 0x4a, 0xd6, 0x00, 0x57, 0x48, 0x90, 0xc6, 0xe6, 0xc6, 0x91,
	0xb5, 0xe7, 0x42, 0x02, 0x95, 0x16, 0x8d, 0xb4, 0x9d, 0xb5, 0x17, 0x55, 0x57, 0x7c, 0x0c, 0xde,
	0x17, 0xad, 0xe4, 0x4c, 0xc4, 0x26, 0x76, 0x13, 0xee, 0x15, 0x81, 0x93, 0xd8, 0xc4, 0x6c, 0x0a,
	0xa3, 0x35, 0x18, 0xb5, 0xa8, 0x32, 0x01, 0x0f, 0xcf, 0xc8, 0xbc, 0x55, 0xf2, 0x73, 0x72, 0x7d,
	0x6f, 0x14, 0xd8, 0x6b, 0x2b, 0x63, 0xf5, 0x4a, 0x3d, 0x84, 0x7f, 0x1a, 0x30, 0x3c, 0x15, 0xc9,
	0x7f, 0xc2, 0x78, 0x04, 0xbb, 0xaa, 0x9a, 0xd5, 0x6c, 0xe1, 0x6c, 0x2f, 0x1a, 0x2c, 0xa2, 0xd6,
	0xa9, 0x2b, 0x54, 0x5a, 0xff, 0x50, 0xa3, 0xbd, 0xa6, 0xc6, 0x1b, 0xc0, 0x55, 0xa8, 0xf5, 0x88,
	0x5e, 0xc0, 0x83, 0x8b, 0x9c, 0xb2, 0x79, 0x1d, 0x8a, 0x4f, 0x01, 0x2c, 0x9a, 0xdb, 0xa2, 0xd0,
	0x11, 0xb5, 0xf8, 0x6c, 0x27, 0xf6, 0x12, 0x06, 0xae, 0x65, 0x2d, 0x28, 0xe1, 0xef, 0x26, 0xc0,
	0xfb, 0xcb, 0xf3, 0xcb, 0xf2, 0x3f, 0x84, 0xc7, 0x00, 0xcb, 0x65, 0x42, 0xe4, 0x1b, 0x2b, 0x19,
	0xec, 0xf1, 0x2d, 0xdb, 0x36, 0x85, 0xc1, 0x1d, 0x6f, 0xe2, 0x88, 0x6f, 0x5b, 0x99, 0xe0, 0x80,
	0x6f, 0xb7, 0x70, 0x08, 0xde, 0xc2, 0x35, 0x38, 0xe4, 0xeb, 0x3e, 0x0d, 0x90, 0x6f, 0x9a, 0xea,
	0x18, 0x60, 0xa9, 0x00, 0x22, 0xdf, 0x70, 0x4e, 0xb0, 0xc7, 0xb7, 0x48, 0xf4, 0x1c, 0xda, 0x76,
	0x50, 0x38, 0xe0, 0xab, 0x1a, 0x04, 0xbb, 0xfc, 0xce, 0xfc, 0x3e, 0x75, 0xec, 0x2f, 0xf9, 0xc5,
	0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x37, 0x3b, 0xe0, 0x41, 0xa7, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NSOServiceClient is the client API for NSOService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NSOServiceClient interface {
	GetDevices(ctx context.Context, in *GetDevicesRequest, opts ...grpc.CallOption) (*GetDevicesResponse, error)
	ExecOperation(ctx context.Context, in *ExecOperationRequest, opts ...grpc.CallOption) (*ExecOperationResponse, error)
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	EditConfig(ctx context.Context, in *EditConfigRequest, opts ...grpc.CallOption) (*EditConfigResponse, error)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
}

type nSOServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNSOServiceClient(cc grpc.ClientConnInterface) NSOServiceClient {
	return &nSOServiceClient{cc}
}

func (c *nSOServiceClient) GetDevices(ctx context.Context, in *GetDevicesRequest, opts ...grpc.CallOption) (*GetDevicesResponse, error) {
	out := new(GetDevicesResponse)
	err := c.cc.Invoke(ctx, "/NSOService/GetDevices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nSOServiceClient) ExecOperation(ctx context.Context, in *ExecOperationRequest, opts ...grpc.CallOption) (*ExecOperationResponse, error) {
	out := new(ExecOperationResponse)
	err := c.cc.Invoke(ctx, "/NSOService/ExecOperation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nSOServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, "/NSOService/GetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nSOServiceClient) EditConfig(ctx context.Context, in *EditConfigRequest, opts ...grpc.CallOption) (*EditConfigResponse, error) {
	out := new(EditConfigResponse)
	err := c.cc.Invoke(ctx, "/NSOService/EditConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nSOServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, "/NSOService/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NSOServiceServer is the server API for NSOService service.
type NSOServiceServer interface {
	GetDevices(context.Context, *GetDevicesRequest) (*GetDevicesResponse, error)
	ExecOperation(context.Context, *ExecOperationRequest) (*ExecOperationResponse, error)
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	EditConfig(context.Context, *EditConfigRequest) (*EditConfigResponse, error)
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
}

// UnimplementedNSOServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNSOServiceServer struct {
}

func (*UnimplementedNSOServiceServer) GetDevices(ctx context.Context, req *GetDevicesRequest) (*GetDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDevices not implemented")
}
func (*UnimplementedNSOServiceServer) ExecOperation(ctx context.Context, req *ExecOperationRequest) (*ExecOperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecOperation not implemented")
}
func (*UnimplementedNSOServiceServer) GetConfig(ctx context.Context, req *GetConfigRequest) (*GetConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}
func (*UnimplementedNSOServiceServer) EditConfig(ctx context.Context, req *EditConfigRequest) (*EditConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditConfig not implemented")
}
func (*UnimplementedNSOServiceServer) Query(ctx context.Context, req *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}

func RegisterNSOServiceServer(s *grpc.Server, srv NSOServiceServer) {
	s.RegisterService(&_NSOService_serviceDesc, srv)
}

func _NSOService_GetDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NSOServiceServer).GetDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NSOService/GetDevices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NSOServiceServer).GetDevices(ctx, req.(*GetDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NSOService_ExecOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NSOServiceServer).ExecOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NSOService/ExecOperation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NSOServiceServer).ExecOperation(ctx, req.(*ExecOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NSOService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NSOServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NSOService/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NSOServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NSOService_EditConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NSOServiceServer).EditConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NSOService/EditConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NSOServiceServer).EditConfig(ctx, req.(*EditConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NSOService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NSOServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NSOService/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NSOServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NSOService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "NSOService",
	HandlerType: (*NSOServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDevices",
			Handler:    _NSOService_GetDevices_Handler,
		},
		{
			MethodName: "ExecOperation",
			Handler:    _NSOService_ExecOperation_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _NSOService_GetConfig_Handler,
		},
		{
			MethodName: "EditConfig",
			Handler:    _NSOService_EditConfig_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _NSOService_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nso_service.proto",
}
